// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package registry

import (
	"github.com/QMDAKA/comment-mock/app/api"
	comment2 "github.com/QMDAKA/comment-mock/handler/rest/comment"
	"github.com/QMDAKA/comment-mock/infrastructure/store/mysql"
	"github.com/QMDAKA/comment-mock/service/comment"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeServer(db *gorm.DB) (api.Server, error) {
	mysqlComment := mysql.ProvideCommentRepo(db)
	commentComment := comment.NewComment(mysqlComment)
	index := comment2.NewCommentIndex(commentComment)
	create := comment2.NewCommentCreate(commentComment)
	handlerCollection := api.NewHandlerCollection(index, create)
	server := api.NewServer(db, handlerCollection)
	return server, nil
}
