// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package registry

import (
	"github.com/QMDAKA/comment-mock/app/api"
	comment2 "github.com/QMDAKA/comment-mock/handler/comment"
	"github.com/QMDAKA/comment-mock/service/comment"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeServer(db *gorm.DB) (api.Server, error) {
	commentComment := comment.NewComment()
	index := comment2.NewCommentIndex(commentComment)
	handlerCollection := api.NewHandlerCollection(index)
	server := api.NewServer(db, handlerCollection)
	return server, nil
}
